### ISSUE TITLE
Throw 500 error if an exception is encountered

### ISSUE THREAD

**Issue by jamessewell** [prometheus/client_python#118] opened 2016-11-17 05:57 UTC
Hello all,

At the moment if a Python exception is encountered it looks like a 200 reponse with a blank body is returned.  This does not result in `up{job='jobname'}` returning 0.

That's fine if you are using an `up_jobname` metric alongside the up metric - but some people dual use the up metric so it means exporter OR app are down (as suggested in the documentation).

An option to choose the behavior would be great.

In the meantime is there a way to explicitly throw a 5xx?

Cheers,
James

**Comment by brian-brazil** [comment] 2016-11-17 14:15
Dupe of #84

**Closed by brian-brazil** 2016-11-17 14:15 UTC
