### ISSUE TITLE
ImportError on make_asgi_app 

### ISSUE THREAD

**Issue by larsclaussen** [prometheus/client_python#550] opened 2020-05-20 13:53 UTC
I'm trying to import the `make_asgi_app` function as stated in the documentation which leads to an exception

```
In [4]: from prometheus_client import make_asgi_app                                                                                           
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-cad669a02132> in <module>
----> 1 from prometheus_client import make_asgi_app

ImportError: cannot import name 'make_asgi_app' from 'prometheus_client' (/usr/local/lib/python3.7/site-packages/prometheus_client/__init__.py)
```
Oh I see it is not included in the release code and the documentation is based on master apparently. Maybe it would be good idea to move the docs to readthedocs or something alike and pin it to a release.

**Comment by brian-brazil** [comment] 2020-05-20 16:43
Dupe of #531

**Closed by brian-brazil** 2020-05-20 16:43 UTC
