### ISSUE TITLE
Pass a custom registry to MetricsHandler

### ISSUE THREAD

**Issue by ioggstream** [prometheus/client_python#222] opened 2017-12-12 16:27 UTC
### I expect

to be able to pass a custom registry to MetricsHandler

### Instead

I can't

### I'd do it

passing the registry to start_http_server

**Comment by brian-brazil** [comment] 2017-12-12 16:41
Dupe of #214

**Closed by brian-brazil** 2017-12-12 16:41 UTC

**Comment by ioggstream** [comment] 2017-12-12 16:49
@brian-brazil as there's probably something I'm missing, it's better to split the patch in two:

- this one for passing the custom registry
- the other one for the multiprocess stuff.
