### ISSUE TITLE
stop_http_server()

### ISSUE THREAD

**Issue by Thomas-2503** [prometheus/client_python#958] opened 2023-09-19 16:24 UTC
Hi :)

Is there a possibility to stop the http_server?
The port can be changed in my application. I want to close the old endpoint and start a new one.
A workaround would be appreciated if there is no possibility to stop the http_server within the prometheus/client_python.
I haven't found a solution here or on stackoverflow that would work.

Thank you!

**Comment by csmarchbanks** [comment] 2023-10-17 21:46
Hello, this is not possible with `start_http_server` today, but would be possible if/when https://github.com/prometheus/client_python/issues/883 is implemented.

Typically if you need more advanced control of the http_server we recommend that you manage the server yourself, see the examples of WSGI/ASGI or Flask in the readme: https://github.com/prometheus/client_python#exporting

I am going to close this as a duplicate of #883, feel free to follow along there if you don't want to manage the server yourself.

**Closed by csmarchbanks** 2023-10-17 21:46 UTC
