### ISSUE TITLE
Cannot execute pushgateway example from README 

### ISSUE THREAD

**Issue by harshitagupta6** [prometheus/client_python#623] opened 2021-02-09 03:55 UTC
code :
from prometheus_client import CollectorRegistry, Gauge,push_to_gateway

registry = CollectorRegistry()
g = Gauge('job_last_success_unixtime', 'Last time a batch job successfully finished', registry=registry)
g.set_to_current_time()
push_to_gateway('localhost:9091', job='batchA', registry=registry)

packages installed: 
pip install prometheus-client

error:
from prometheus_client import CollectorRegistry, Gauge,push_to_gateway
ImportError: cannot import name 'push_to_gateway' from 'prometheus_client' (/Users/hvj/Desktop/test/prometheus/test_prometheus/lib/python3.9/site-packages/prometheus_client/__init__.py)

**Comment by csmarchbanks** [comment] 2021-02-09 17:38
Hello, I am afraid I am unable to reproduce this issue locally or in a python 3.9 docker container. Can you provide a bit more information, such as what version of the prometheus_client you are running, and anything else that might be non-standard?

**Comment by csmarchbanks** [comment] 2021-04-15 23:33
Closing as not reproducible. If someone can provide steps to reproduce, I am happy to reopen this issue.

**Closed by csmarchbanks** 2021-04-15 23:33 UTC
