### ISSUE TITLE
Unexpected behaviour around registries and Gauge constructor

### ISSUE THREAD

**Issue by lulzmachine** [prometheus/client_python#549] opened 2020-05-20 13:25 UTC
Hello!

Thanks for the great library! We've used to great success to gather metrics for various python services. But we have also stumbled upon some quite unexpected behaviour when figuring out how to use it. Here is some example code (using 0.7.1):

```
from prometheus_client import (
    CollectorRegistry,
    Gauge,
    pushadd_to_gateway,
    generate_latest,
)
labels = ['namespace']
label_values = ['dev']

# 1
registry = CollectorRegistry()
gauge = Gauge("example", "Example gauge", registry=registry, labelnames=labels)
gauge.labels(label_values).set(5)

print(generate_latest(registry))
# HELP example Example gauge\n# TYPE example gauge\nexample{namespace="[\'dev\']"} 5.0\n'
# Contains gauge, with labels. As expected.


# -----------------
# 2
registry = CollectorRegistry()
gauge = Gauge(
    "example",
    "Example gauge",
    registry=registry,
    labelnames=labels,
    labelvalues=label_values,
)
gauge.set(5)

print(generate_latest(registry))
# b''
# Gauge is never added to registry if we supply "labelvalues". This is unexpected, and not mentioned by a warning log or so.

# -----------------
# 3
registry = CollectorRegistry()
gauge = Gauge(
    "example",
    "Example gauge",
    registry=registry,
    labelnames=labels,
    labelvalues=label_values,
)
gauge.set(5)

registry.register(gauge)

print(generate_latest(registry))
# b'# HELP example Example gauge\n# TYPE example gauge\nexample 5.0\n'
# Contains the gauge, but the value is *not* set to the correct label
```

We have found that behaviour # 2 seems to be deliberately programmed, but we can't figure out what the reasoning is:

```
# metrics.py
class MetricWrapperBase(object):
    def __init__(self,
        [...snip...]
        if not self._labelvalues:
            # Register the multi-wrapper parent metric, or if a label-less metric, the whole shebang.    
            if registry:
                registry.register(self)
```

**Comment by brian-brazil** [comment] 2020-05-20 16:43
This is a dupe of #398, users specifying labelvalues is not supported nor documented.

**Closed by brian-brazil** 2020-05-20 16:43 UTC
