### ISSUE TITLE
Pushing to PushGateway is not pushing any metrics

### ISSUE THREAD

**Issue by ricardoatsouza** [prometheus/client_python#659] opened 2021-05-28 09:34 UTC
Hello,

I have a set of metrics in my batch job, all of them being created in the following way:
```python
    r = CollectorRegistry()
    ...
    c = Counter(<name>, <description>, registry=r, labelnames=<global_label_names>, labelvalues=<global_label_values>)
```

In my use case, I have a small set of _global_ labels that I define to every metric when they are created. Then, at the end of the batch job, the metrics are pushed to PushGateway through the `push_to_gateway` function. The command runs successfully. However, in PushGateway, none of the metrics is actually there.

```python
    push_to_gateway(<url>, job=<job_name>, registry=r)
```

While trying to understand why, I crossed with [this line in the code](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics.py#L118). Basically, the created metrics are _only added to the given registry `r` when there are no labels given to it_. Consequently, the registry `r` is empty when `push_to_gateway` runs.

I wonder if this is the intended behaviour. In case positive, is there a way to use the global prometheus registry in `push_to_gateway` (`registry` is a required parameter in the function call)?

**Comment by roidelapluie** [comment] 2021-05-28 11:53
`labelvalues=<global_label_values>` is an internal parameter (it is not mentioned in the documentation). Please look at the documentation for proper usage of counters. In particular, I think you need to call `Counter.labels()` to set the label values.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by csmarchbanks** [comment] 2021-05-28 16:32
Hello, this is a duplicate of https://github.com/prometheus/client_python/issues/398, I have also created https://github.com/prometheus/client_python/pull/660 to close that issue and make it clear that labelvalues is for internal use only.

**Closed by csmarchbanks** 2021-05-28 16:32 UTC

**Comment by ricardoatsouza** [comment] 2021-06-03 12:56
@roidelapluie Thanks for the quick answer. Sorry if I couldn't reply earlier. It would be indeed beneficial if the documentation explicitly say that this is intended for internal use. 

What I would like to achieve is to define a set of fixed values for my counter (or histogram, etc). Those values do change on every execution of the batch process and are not dimensionally big. I saw in the documentation that I can create the labels using `label_names`, but then I would have to assign their values using `labels` every time I would call `inc`.

That's a small use case, and I am not sure whether it happens often enough to justify its implementation. 🤷‍♂️

**Comment by csmarchbanks** [comment] 2021-06-03 15:53
Hello, that is certainly a reasonable use case, and I wonder if this library covers it well enough as is. If not, we can create a new issue that is an enhancement request. Currently the way to create a metric with a fixed set of labels would be like this:
```
c = Counter(
    "my_requests_total",
    "HTTP Failures",
    ["method", "endpoint"],
).labels("get", "/")
c.inc()
```
Does a workflow like that enable what you require?

**Comment by ricardoatsouza** [comment] 2021-06-04 13:50
Hello @csmarchbanks. Naive if me not to think of your proposal. It seems to work just fine. If I encounter issues, I might come back, but for now the case is closed. Thanks!

**Comment by roidelapluie** [comment] 2021-06-04 15:08
Awesome 🥳
