### ISSUE TITLE
E1120:No value for argument 'labelvalues' in constructor call?

### ISSUE THREAD

**Issue by jeffwji** [prometheus/client_python#229] opened 2017-12-20 17:15 UTC
Hi

The example provided can't be compiled due to "E1120:No value for argument 'labelvalues' in constructor call" for Summary class at this line.

`REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')`

Constructor is defined as 

`    def __init__(self, name, labelnames, labelvalues):`

What value should be provided for the `labelvalues`?

**Comment by brian-brazil** [comment] 2017-12-20 17:20
Are you sure that's a compiler error?

**Comment by jeffwji** [comment] 2017-12-20 18:10
Actually it comes from pylint.

**Comment by brian-brazil** [comment] 2017-12-20 18:33
Dupe of #210

**Closed by brian-brazil** 2017-12-20 18:33 UTC
